# Reconstruction-only fine-tuning on ZJNUCrack, 4x.
# total_iter 200000 is SR-FT. total_iter 600000 is SR-FT+.
name: LPSRNet_ZJNUCrack_FT_x4
model_type: LongitudinalSRModel
scale: 4
num_gpu: auto
manual_seed: 10

datasets:
  train:
    name: ZJNUCrack
    type: LongitudinalPairedDataset
    dataroot_gt: datasets/ZJNUCrack/train/HR
    dataroot_lq: datasets/ZJNUCrack/train/LR/x4
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size_h: 256
    gt_size_w: 256
    use_hflip: true
    use_vflip: true
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ZJNUCrack_val
    type: LongitudinalPairedDataset
    dataroot_gt: datasets/ZJNUCrack/val/HR
    dataroot_lq: datasets/ZJNUCrack/val/LR/x4
    filename_tmpl: '{}'
    io_backend:
      type: disk

network_g:
  type: LPSRNet
  dim: 36
  n_blocks: 8
  ffn_scale: 2
  upscaling_factor: 4
  in_channels: 1
  out_channels: 1
  gafmb_index: 3
  use_ea: true
  use_pdcfn: true
  use_pps: true
  pool_size: 8

path:
  pretrain_network_g: experiments/LPSRNet_SACrack_x4/models/net_g_latest.pth
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepRestartLR
    milestones: [200000, 400000]
    gamma: 0.1
  total_iter: 600000
  warmup_iter: -1
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

val:
  val_freq: !!float 5000
  save_img: false
  pbar: false
  tile_size: [128, 512]
  tile_overlap: 16
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
